#!/bin/sh /etc/rc.common
START=99
STOP=10
USE_PROCD=1
PROG="/usr/bin/forward-loop-sms.sh"

start_service(){
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn 2000 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
